### ISSUE TITLE
Cake Pattern and Dependency Injection

### ISSUE THREAD

**Issue by lerencao** [lerencao/notes#17]
[Cake Pattern in Scala / Self type annotations / Explicitly Typed Self References - explained](https://coderwall.com/p/t_rapw)

[real world scala dependency injection di](http://jonasboner.com/2008/10/06/real-world-scala-dependency-injection-di/)

[cake pattern in depth](http://www.cakesolutions.net/teamblogs/2011/12/19/cake-pattern-in-depth)

[Dependency Injection in Scala: Extending the Cake Pattern](http://www.warski.org/blog/2010/12/di-in-scala-cake-pattern/)

**Comment by nanne007** [comment]
-
