### ISSUE TITLE
ss 不同实现的坑

### ISSUE THREAD

**Issue by lerencao** [lerencao/notes#82]
昨天我的 SS 服务器又被强了。事实证明，没有一台能够活过半年。这一次是五个月。

每次配置SS，都得重来一遍，甚是蛋疼。

上次用的 golang 编译的版本，参数配置貌似没啥问题，没映像了。应该很顺利。

这次换了 libuv 版本，ipv6 的配置不能用了。

搜了搜，发现原来需要这样配置。 https://github.com/shadowsocks/shadowsocks-libev/issues/254

```
"server":["[::0]", "0.0.0.0"],
```

厉害了，我的哥。

**Comment by kennylawww** [comment]
原先python的实现只要指定为"::"就可以了
