### ISSUE TITLE
TiDB 对网络很敏感

### ISSUE THREAD

**Issue by lerencao** [lerencao/notes#96]
昨天公司运维那边做交换机做了优化，retransmit seg 基本减少到无。

同时，我这边监控的TiDB Slow Query 也减少了很多。

![image](https://user-images.githubusercontent.com/1456096/57346745-4c38f880-7182-11e9-8c20-077eb2f12115.png)

之前做优化，慢SQL 减到一定程度就减不下去了。之前以为是受存储（SATA 盘）性能影响。
现在看，网络因素占了绝大部分。
奇怪的是看监控，节点的 tcp retrans 一直都有，但保持在很低的水平。
原来正常的就是应该没有，或者很少。

![image](https://user-images.githubusercontent.com/1456096/57346920-0f213600-7183-11e9-8829-56a30131f8df.png)

**Comment by ariwaranosai** [comment]
居然把公司内部的信息截图放出来。

**Comment by lerencao** [comment]
又没有任何公司的信息。

**Comment by michelia** [comment]
tidb中的慢查询把网络传输的时间算上了, 即 tidb接受到sql, 到客户端获取完所有sql结果, 这中间包含了`sql结果`的网络传输时间
